---
- hosts: all
  become: yes
  roles:
          - {role: Install_mariadb}
- hosts: master1
  become: yes
  roles:
          - {role: Config_Master}
          - {role: Config_MySql}
          - {role: Create_User}
          - {role: Bootstrap}
- hosts: master2
  become: yes
  roles:
          - {role: Config_MySql}
          - {role: Create_User}
          - {role: join_repli}
